# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FBInstruction

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Instructions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Instructions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInstructions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Instructions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Instructions
    def Instructions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FBInstruction.Instruction import Instruction
            obj = Instruction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Instructions
    def InstructionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Instructions
    def InstructionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def InstructionsStart(builder):
    builder.StartObject(1)

def Start(builder):
    InstructionsStart(builder)

def InstructionsAddInstructions(builder, instructions):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(instructions), 0)

def AddInstructions(builder, instructions):
    InstructionsAddInstructions(builder, instructions)

def InstructionsStartInstructionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInstructionsVector(builder, numElems: int) -> int:
    return InstructionsStartInstructionsVector(builder, numElems)

def InstructionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return InstructionsEnd(builder)
